using Shojy.FF7.Reno.Models.Enums;

namespace Shojy.FF7.Reno.Models;

[PublicAPI]
public static class Lookups
{
    private static readonly Dictionary<KeyItems, int> _keyItemIds = new()
    {
        {KeyItems.CottonDress,  0},
        {KeyItems.SatinDress,  1},
        {KeyItems.SilkDress,  2},
        {KeyItems.Wig,  3},
        {KeyItems.DyedWig,  4},
        {KeyItems.BlondeWig,  5},
        {KeyItems.GlassTiara,  6},
        {KeyItems.RubyTiara,  7},
        {KeyItems.DiamondTiara,  8},
        {KeyItems.Cologne,  9},
        {KeyItems.FlowerCologne, 10},
        {KeyItems.SexyCologne, 11},
        {KeyItems.MembersCard, 12},
        {KeyItems.Lingerie, 13},
        {KeyItems.MysteryPanties, 14},
        {KeyItems.BikiniBriefs, 15},
        {KeyItems.PharmacyCoupon, 16},
        {KeyItems.Disinfectant, 17},
        {KeyItems.Deodorant, 18},
        {KeyItems.Digestive, 19},
        {KeyItems.HugeMateriaFortCondor, 20},
        {KeyItems.HugeMateriaCorel, 21},
        {KeyItems.HugeMateriaUnderwater, 22},
        {KeyItems.HugeMateriaRocket, 23},
        {KeyItems.KeyToAncients, 24},
        {KeyItems.LetterToADaughter, 25},
        {KeyItems.LetterToAWife, 26},
        {KeyItems.LunarHarp, 27},
        {KeyItems.BasementKey, 28},
        {KeyItems.KeyToSector5, 29},
        {KeyItems.Keycard60, 30},
        {KeyItems.Keycard62, 31},
        {KeyItems.Keycard65, 32},
        {KeyItems.Keycard66, 33},
        {KeyItems.Keycard68, 34},
        {KeyItems.MidgarParts1, 35},
        {KeyItems.MidgarParts2, 36},
        {KeyItems.MidgarParts3, 37},
        {KeyItems.MidgarParts4, 38},
        {KeyItems.MidgarParts5, 39},
        {KeyItems.PHS, 40},
        {KeyItems.GoldTicket, 41},
        {KeyItems.Keystone, 42},
        {KeyItems.LeviathanScales, 43},
        {KeyItems.GlacierMap, 44},
        {KeyItems.ACoupon, 45},
        {KeyItems.BCoupon, 46},
        {KeyItems.CCoupon, 47},
        {KeyItems.BlackMateria, 48},
        {KeyItems.Mythril, 49},
        {KeyItems.Snowboard, 50},
        {KeyItems.KeyItem52, 51},
        {KeyItems.KeyItem53, 52},
        {KeyItems.KeyItem54, 53},
        {KeyItems.KeyItem55, 54},
        {KeyItems.KeyItem56, 55},
        {KeyItems.KeyItem57, 56},
        {KeyItems.KeyItem58, 57},
        {KeyItems.KeyItem59, 58},
        {KeyItems.KeyItem60, 59},
        {KeyItems.KeyItem61, 60},
        {KeyItems.KeyItem62, 61},
        {KeyItems.KeyItem63, 62},
        {KeyItems.KeyItem64, 63},
    };
    public static IReadOnlyDictionary<KeyItems, int> KeyItemIds => _keyItemIds;
}